"""
QuantDB Authentication & Authorization Package.
"""

from src.auth.email_service import send_otp_email, set_test_email_sender
from src.auth.otp import generate_otp, hash_otp, verify_otp_hash
from src.auth.password import hash_password, verify_password
from src.auth.roles import (
    Role,
    ROLE_DISPLAY_NAMES,
    ROLE_ALLOWED_PAGES,
    get_role_display_name,
    get_allowed_pages,
    has_page_access,
    normalize_role,
    can_trade,
    can_backtest,
    can_manage_strategies,
    can_manage_users,
)
from src.auth.service import (
    AuthenticationError,
    AccountInactiveError,
    UnverifiedEmailError,
    AuthorizationError,
    RegistrationError,
    OTPError,
    OTPExpiredError,
    OTPCooldownError,
    OTPVerificationError,
    authenticate_user,
    register_user,
    verify_registration_otp,
    resend_registration_otp,
    validate_registration_data,
    validate_password_strength,
    get_user_role,
    has_permission,
    require_role,
)

__all__ = [
    "hash_password",
    "verify_password",
    "Role",
    "ROLE_DISPLAY_NAMES",
    "ROLE_ALLOWED_PAGES",
    "get_role_display_name",
    "get_allowed_pages",
    "has_page_access",
    "normalize_role",
    "can_trade",
    "can_backtest",
    "can_manage_strategies",
    "can_manage_users",
    "AuthenticationError",
    "AccountInactiveError",
    "UnverifiedEmailError",
    "AuthorizationError",
    "RegistrationError",
    "OTPError",
    "OTPExpiredError",
    "OTPCooldownError",
    "OTPVerificationError",
    "authenticate_user",
    "register_user",
    "verify_registration_otp",
    "resend_registration_otp",
    "validate_registration_data",
    "validate_password_strength",
    "generate_otp",
    "hash_otp",
    "verify_otp_hash",
    "send_otp_email",
    "set_test_email_sender",
    "get_user_role",
    "has_permission",
    "require_role",
]
